### ISSUE TITLE
Crash issue on withTrashed not fixed

### ISSUE THREAD

**Issue by FaridAghili** [optimistdigital/nova-sortable#49]
@Tarpsvo https://github.com/optimistdigital/nova-sortable/commit/b088d34bd5d7a077563ece81f907ca08882f39c2 didn't fixed https://github.com/optimistdigital/nova-sortable/issues/48 and I guess `is_callable` is returning True on non SoftDeletes because of Eloquent's magic methods.

Just use `method_exists` instead of `is_callable`, I've tested this with and without `SoftDeletes` trait.

**Comment by Tarpsvo** [comment]
Hi! Seems to work, released in version 1.4.17.

**Comment by andre4nap** [comment]
The best way to determine if a model has Soft Deletes trait is to check `trashed()` method instead of `withTrashed()`.

You can check it here
[https://laravel.com/docs/8.x/eloquent#soft-deleting](https://laravel.com/docs/8.x/eloquent#soft-deleting).

I reopen this issue because my laravel version doesn't return true on `method_exists`. Can you update please?

**Comment by Tarpsvo** [comment]
I merged your PR @andre4nap. Thanks for helping out and good luck!
