### ISSUE TITLE
Hide sort button (instead of disabling it)

### ISSUE THREAD

**Issue by salvisb** [optimistdigital/nova-sortable#77]
Hi, is it somehow possible to hide the sort button from index (instead of disabling it) and only show it for relationships on a detail screen? Thanks!

**Comment by Tarpsvo** [comment]
Hey! This might've been a side effect of a recent series of bugs in version 2.1.5. Please upgrade to 2.1.6 and let me know if the issue persists. Thank you and good luck!

**Comment by salvisb** [comment]
Upgrading to 2.1.6 fixed the issue. Thanks!

**Comment by AforDesign** [comment]
This behavior has returned.
I'm not sure since when, might be this way for a long time.

**More information on my setup:**

laravel/framework 11.43.2
laravel/nova 4.35.6
outl1ne/nova-sortable 3.4.7

Models / Resources with ManyToMany (BelongsToMany) relation:
-Category
-Product
-Option

Products should be sortable on te Category Detail View and not on the Option Detail View.
The HasSortableManyToManyRows is used on the Product Resource.

Setting the $sortable property doesn't seem to work (I tried using 'only_sort_on' and 'dont_sort_on' only):
```
public array $sortable = [
    'only_sort_on' => Category::class,
    'dont_sort_on' => [
        Option::class
    ]
 ];
```

Using the canSort method does work.
But it disable the sorting icons instead of hiding it:
```
public static function canSort(NovaRequest $request, $resource): bool {
      return $request->viaResource === Category::uriKey();
}
```


Btw. Thank you for developing and maintaining this super useful plugin!
